# Utilisez l'image officielle de PostGIS
FROM postgis/postgis:15-3.3

# Install packages that contains shp2pgsql
RUN set -eux \
      && apt-get update \
      && apt-get install -y --no-install-recommends \
           postgis \
           gdal-bin \
           unzip \
      && dpkg -L postgis \     
      && rm -rf /var/lib/apt/lists/*
      
# Copiez le fichier GeoJSON et le script d'importation
COPY data.geojson /docker-entrypoint-initdb.d/data.geojson
COPY import.sh /docker-entrypoint-initdb.d/import.sh

# Donnez les droits d'exécution au script
RUN chmod +x /docker-entrypoint-initdb.d/import.sh
