ARG BASE_IMAGE_TAG=16-3.4

FROM postgis/postgis:${BASE_IMAGE_TAG}

# Install packages that contains shp2pgsql
RUN set -eux \
      && apt-get update \
      && apt-get install -y --no-install-recommends \
           postgis \
           gdal-bin \
           unzip \
      && dpkg -L postgis \     
      && rm -rf /var/lib/apt/lists/*

# Copy the shapefile and the load script into the image
# COPY ./data /shapefiles
COPY ./data/admin_0_countries.zip /shapefiles/
COPY ./load_shapefile.sh /docker-entrypoint-initdb.d/20-load_shapefile.sh

# COPY the geojson files
COPY ./data/geojson /geojson


RUN unzip /shapefiles/admin_0_countries.zip -d /shapefiles
RUN rm -rf /shapefiles/admin_0_countries.zip

# Make the script executable
RUN chmod +x /docker-entrypoint-initdb.d/20-load_shapefile.sh

# Ajouter une ligne au fichier pg_hba.conf
# RUN echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf

# Expose the PostgreSQL port
EXPOSE 5432
