services:
  qgis-server:
    build: qgis-server
    volumes:
      - ${PWD}/qgis-server/data:/data:ro
    environment:
      - LANG=en_EN.UTF-8
      - QGIS_PROJECT_FILE=/data/osm.qgs
      - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
      - DEBUG=1                  # display env before spawning QGIS Server
    depends_on:
      - postgis

  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-server

  postgis:
    build: postgis
    volumes:
        - postgis_data:/var/lib/postgresql/data
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - ALLOW_IP_RANGE=0.0.0.0/0
      # - PGDATA=/var/lib/postgresql/data/some_name/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgis -p 5432 -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgis

volumes:
  postgis_data: