services:
  qgis-server:
    build: qgis-server
    volumes:
      - ${PWD}/qgis-server/data:/data
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - LANG=en_EN.UTF-8
      - QGIS_PROJECT_FILE=/data/dailymaps.qgs
      - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
      - QGIS_SERVER_CACHE_SIZE=268435456
      - DEBUG=1                  # display env before spawning QGIS Server
    depends_on:
      - postgis

  nginx:
    image: nginx # :1.13
    ports:
      - 8080:80
    volumes:
      # - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/nginx/index.html:/usr/share/nginx/html/index.html
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-server

  postgis:
    build: postgis
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - ALLOW_IP_RANGE=0.0.0.0/0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgis -p 5432 -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ${PWD}/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8081:80"
    depends_on:
      - postgis
